# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[dotnet]
format = '(via [$symbol($version )(🎯 $tfm )]($style))'

[nodejs]
symbol = "[⬢](bold green) "
format = '(via [$symbol($version )]($style))'

[rust]
format = '(via [$symbol($version )]($style))'
